// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service.proto

package company

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CreateCompanyReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *CreateCompanyReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for Descriptioon

	return nil
}

// CreateCompanyReqValidationError is the validation error returned by
// CreateCompanyReq.Validate if the designated constraints aren't met.
type CreateCompanyReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCompanyReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCompanyReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCompanyReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCompanyReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCompanyReqValidationError) ErrorName() string { return "CreateCompanyReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateCompanyReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCompanyReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCompanyReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCompanyReqValidationError{}

// Validate checks the field values on CreateCompanyRes with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *CreateCompanyRes) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Status

	// no validation rules for Id

	return nil
}

// CreateCompanyResValidationError is the validation error returned by
// CreateCompanyRes.Validate if the designated constraints aren't met.
type CreateCompanyResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCompanyResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCompanyResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCompanyResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCompanyResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCompanyResValidationError) ErrorName() string { return "CreateCompanyResValidationError" }

// Error satisfies the builtin error interface
func (e CreateCompanyResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCompanyRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCompanyResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCompanyResValidationError{}
